version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - "/functions/go-function/"
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: "/functions/python-function/"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      - dependency-name: "actions/checkout"
        versions: [">=6.0.2"]
      - dependency-name: "actions/setup-node"
        versions: [">=6.2.0"]
      - dependency-name: "actions/setup-python"
        versions: [">=6.1.0"]
      - dependency-name: "actions/setup-go"
        versions: [">=6.2.0"]
      - dependency-name: "actions/upload-artifact"
        versions: [">=6.0.0"]
